Run tests on MacOS in CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,9 @@ jobs:
           - os: ubuntu-20.04
             pg_major: 13
             config: Debug
+          - os: macos-11
+            pg_major: 13
+            config: Release
           - os: ubuntu-20.04
             pg_major: 14
             config: Release
@@ -70,7 +73,7 @@ jobs:
           sudo apt-get install -qq postgresql-${{ matrix.pg_major }}
           export PGDATA=/etc/postgresql/${{ matrix.pg_major }}/main
           # Starting with PG14 the default password encryption mode is scram.
-          # Changing it to md5 for compatability.
+          # Changing it to md5 for compatibility.
           if [ ${{ matrix.pg_major }} -ge 14 ]; then
             sudo sed -i 's/#password_encryption = scram-sha-256/password_encryption = md5/' $PGDATA/postgresql.conf
           fi
@@ -126,8 +129,7 @@ jobs:
           unzip pgsql.zip -x 'pgsql/include/**' 'pgsql/doc/**' 'pgsql/pgAdmin 4/**' 'pgsql/StackBuilder/**'
 
           # Match Npgsql CI Docker image and stash one level up
-          cp {$GITHUB_WORKSPACE/.build,pgsql}/server.crt
-          cp {$GITHUB_WORKSPACE/.build,pgsql}/server.key
+          cp $GITHUB_WORKSPACE/.build/{server.crt,server.key} pgsql
 
           # Find OSGEO version number
           OSGEO_VERSION=$(\
@@ -153,9 +155,9 @@ jobs:
           sed -i "s|#synchronous_standby_names =|synchronous_standby_names = 'npgsql_test_sync_standby' #|" pgsql/PGDATA/postgresql.conf
           sed -i "s|#synchronous_commit =|synchronous_commit = local #|" pgsql/PGDATA/postgresql.conf
           pgsql/bin/pg_ctl -D pgsql/PGDATA -l logfile -o '-c ssl=true -c ssl_cert_file=../server.crt -c ssl_key_file=../server.key' start
-          
+
           # Starting with PG14 the default password encryption mode is scram.
-          # Changing it to md5 for compatability.
+          # Changing it to md5 for compatibility.
           if [ ${{ matrix.pg_major }} -ge 14 ]; then
             sed -i "s|#password_encryption = scram-sha-256|password_encryption = md5|" pgsql/PGDATA/postgresql.conf
           fi
@@ -185,12 +187,79 @@ jobs:
           echo "host all all all md5" >> pgsql/PGDATA/pg_hba.conf
           echo "host replication all all md5" >> pgsql/PGDATA/pg_hba.conf
 
+      - name: Start PostgreSQL ${{ matrix.pg_major }} (MacOS)
+        if: startsWith(matrix.os, 'macos')
+        run: |
+            PGDATA=/usr/local/var/postgres
+
+            sudo sed -i '' 's/#ssl = off/ssl = on/' $PGDATA/postgresql.conf
+            cp $GITHUB_WORKSPACE/.build/{server.crt,server.key} $PGDATA
+            chmod 600 $PGDATA/{server.crt,server.key}
+
+            # Starting with PG14 the default password encryption mode is scram.
+            # Changing it to md5 for compatibility.
+            if [ ${{ matrix.pg_major }} -ge 14 ]; then
+              sudo sed -i 's/#password_encryption = scram-sha-256/password_encryption = md5/' $PGDATA/postgresql.conf
+            fi
+
+            brew services start postgresql
+            echo "Check PostgreSQL service is running"
+            i=5
+            COMMAND='pg_isready'
+            while [ $i -gt 0 ]; do
+                echo "Check PostgreSQL service status"
+                eval $COMMAND && break
+                ((i--))
+                if [ $i == 0 ]; then
+                    echo "PostgreSQL service not ready, all attempts exhausted"
+                    exit 1
+                fi
+                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+                sleep 5
+            done
+            psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'npgsql_tests'" postgres
+
+            if [ ${{ matrix.pg_major }} -ge 14 ]; then
+              sudo sed -i '' 's/password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
+            else
+              sudo sed -i '' 's/#password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
+            fi
+            sudo sed -i '' 's/#wal_level =/wal_level = logical #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#max_wal_senders =/max_wal_senders = 50 #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#logical_decoding_work_mem =/logical_decoding_work_mem = 64kB #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#wal_sender_timeout =/wal_sender_timeout = 3s #/' $PGDATA/postgresql.conf
+            sudo sed -i '' "s/#synchronous_standby_names =/synchronous_standby_names = 'npgsql_test_sync_standby' #/" $PGDATA/postgresql.conf
+            sudo sed -i '' "s/#synchronous_commit =/synchronous_commit = local #/" $PGDATA/postgresql.conf
+            # Disable trust authentication, requiring MD5 passwords - some tests must fail if a password isn't provided.
+            sudo sh -c "echo 'local all all trust' > $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host all npgsql_tests_scram all scram-sha-256' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
+
+            brew services restart postgresql
+            echo "Check PostgreSQL service is running"
+            i=5
+            COMMAND='pg_isready'
+            while [ $i -gt 0 ]; do
+                echo "Check PostgreSQL service status"
+                eval $COMMAND && break
+                ((i--))
+                if [ $i == 0 ]; then
+                    echo "PostgreSQL service not ready, all attempts exhausted"
+                    exit 1
+                fi
+                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+                sleep 5
+            done
+            psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'" postgres
+
       # TODO: Once test/Npgsql.Specification.Tests work, switch to just testing on the solution
       - name: Test
         run: dotnet test -c ${{ matrix.config }} test/Npgsql.Tests --logger "GitHubActions;report-warnings=false"
         shell: bash
 
       - name: Test Plugins
+        if: "!startsWith(matrix.os, 'macos')"
         run: |
             if [ -z "${{ matrix.pg_prerelease }}" ]; then
                 dotnet test -c ${{ matrix.config }} test/Npgsql.PluginTests --logger "GitHubActions;report-warnings=false"
