Sync CI macos setup to latest main

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -216,63 +216,74 @@ jobs:
       - name: Start PostgreSQL ${{ matrix.pg_major }} (MacOS)
         if: startsWith(matrix.os, 'macos')
         run: |
-          # First uninstall any PostgreSQL installed on the image
-          dpkg-query -W --showformat='${Package}\n' 'postgresql-*' | xargs sudo dpkg -P postgresql
-
-          # Import the repository signing key
-          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
-
-          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main ${{ matrix.pg_major }}" >> /etc/apt/sources.list.d/pgdg.list'
-          sudo apt-get update -qq
-          sudo apt-get install -qq postgresql-${{ matrix.pg_major }}
-          export PGDATA=/etc/postgresql/${{ matrix.pg_major }}/main
+            brew install postgresql@${{ matrix.pg_major }}
           
-          sudo cp $GITHUB_WORKSPACE/.build/{server.crt,server.key} $PGDATA
-          sudo chmod 600 $PGDATA/{server.crt,server.key}
-          sudo chown postgres $PGDATA/{server.crt,server.key}
-          
-          # Create npgsql_tests user with md5 password 'npgsql_tests'
-          sudo -u postgres psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'md5adf74603a5772843f53e812f03dacb02'"
-          
-          sudo -u postgres psql -c "CREATE USER npgsql_tests_ssl SUPERUSER PASSWORD 'npgsql_tests_ssl'"
-          sudo -u postgres psql -c "CREATE USER npgsql_tests_nossl SUPERUSER PASSWORD 'npgsql_tests_nossl'"
+            PGDATA=/opt/homebrew/var/postgresql@${{ matrix.pg_major }}
 
-          # To disable PostGIS for prereleases (because it usually isn't available until late), surround with the following:
-          if [ -z "${{ matrix.pg_prerelease }}" ]; then
-            sudo apt-get install -qq postgresql-${{ matrix.pg_major }}-postgis-${{ env.postgis_version }}
-          fi
-          
-          if [ ${{ matrix.pg_major }} -ge 14 ]; then
-            sudo sed -i "s|unix_socket_directories = '/var/run/postgresql'|unix_socket_directories = '/var/run/postgresql, @/npgsql_unix'|" $PGDATA/postgresql.conf
-          fi
+            sudo sed -i '' 's/#ssl = off/ssl = on/' $PGDATA/postgresql.conf
+            cp $GITHUB_WORKSPACE/.build/{server.crt,server.key} $PGDATA
+            chmod 600 $PGDATA/{server.crt,server.key}
+            
+            postgreService=$(brew services list | grep -oe "postgresql@${{ matrix.pg_major }}\S*")
 
-          sudo sed -i 's/max_connections = 100/max_connections = 500/' $PGDATA/postgresql.conf
-          sudo sed -i 's/#ssl = off/ssl = on/' $PGDATA/postgresql.conf
-          sudo sed -i "s|ssl_cert_file =|ssl_cert_file = '$PGDATA/server.crt' #|" $PGDATA/postgresql.conf
-          sudo sed -i "s|ssl_key_file =|ssl_key_file = '$PGDATA/server.key' #|" $PGDATA/postgresql.conf
-          sudo sed -i 's/#password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
-          sudo sed -i 's/#wal_level =/wal_level = logical #/' $PGDATA/postgresql.conf
-          sudo sed -i 's/#max_wal_senders =/max_wal_senders = 50 #/' $PGDATA/postgresql.conf
-          sudo sed -i 's/#logical_decoding_work_mem =/logical_decoding_work_mem = 64kB #/' $PGDATA/postgresql.conf
-          sudo sed -i 's/#wal_sender_timeout =/wal_sender_timeout = 3s #/' $PGDATA/postgresql.conf
-          sudo sed -i "s/#synchronous_standby_names =/synchronous_standby_names = 'npgsql_test_sync_standby' #/" $PGDATA/postgresql.conf
-          sudo sed -i "s/#synchronous_commit =/synchronous_commit = local #/" $PGDATA/postgresql.conf
-          sudo sed -i "s/#max_prepared_transactions = 0/max_prepared_transactions = 100/" $PGDATA/postgresql.conf
+            brew services start $postgreService
+            export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
+            echo "Check PostgreSQL service is running"
+            i=5
+            COMMAND='pg_isready'
+            while [ $i -gt 0 ]; do
+                echo "Check PostgreSQL service status"
+                eval $COMMAND && break
+                ((i--))
+                if [ $i == 0 ]; then
+                    echo "PostgreSQL service not ready, all attempts exhausted"
+                    exit 1
+                fi
+                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+                sleep 5
+            done
+            
+            # Create npgsql_tests user with md5 password 'npgsql_tests'
+            psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'md5adf74603a5772843f53e812f03dacb02'" postgres
+            
+            psql -c "CREATE USER npgsql_tests_ssl SUPERUSER PASSWORD 'npgsql_tests_ssl'" postgres
+            psql -c "CREATE USER npgsql_tests_nossl SUPERUSER PASSWORD 'npgsql_tests_nossl'" postgres
 
-          # Disable trust authentication, requiring MD5 passwords - some tests must fail if a password isn't provided.
-          sudo sh -c "echo 'local all all trust' > $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'host all npgsql_tests_scram all scram-sha-256' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'hostssl all npgsql_tests_ssl all md5' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'hostnossl all npgsql_tests_ssl all reject' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'hostnossl all npgsql_tests_nossl all md5' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'hostssl all npgsql_tests_nossl all reject' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
-          sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
-          
-          sudo pg_ctlcluster ${{ matrix.pg_major }} main restart
+            sudo sed -i '' 's/max_connections = 100/max_connections = 500/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#password_encryption = md5/password_encryption = scram-sha-256/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#wal_level =/wal_level = logical #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#max_wal_senders =/max_wal_senders = 50 #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#logical_decoding_work_mem =/logical_decoding_work_mem = 64kB #/' $PGDATA/postgresql.conf
+            sudo sed -i '' 's/#wal_sender_timeout =/wal_sender_timeout = 3s #/' $PGDATA/postgresql.conf
+            sudo sed -i '' "s/#synchronous_standby_names =/synchronous_standby_names = 'npgsql_test_sync_standby' #/" $PGDATA/postgresql.conf
+            sudo sed -i '' "s/#synchronous_commit =/synchronous_commit = local #/" $PGDATA/postgresql.conf
+            sudo sed -i '' "s/#max_prepared_transactions = 0/max_prepared_transactions = 100/" $PGDATA/postgresql.conf
+            # Disable trust authentication, requiring MD5 passwords - some tests must fail if a password isn't provided.
+            sudo sh -c "echo 'local all all trust' > $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'hostssl all npgsql_tests_ssl all md5' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'hostnossl all npgsql_tests_ssl all reject' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'hostnossl all npgsql_tests_nossl all md5' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'hostssl all npgsql_tests_nossl all reject' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host all npgsql_tests_scram all scram-sha-256' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host all all all md5' >> $PGDATA/pg_hba.conf"
+            sudo sh -c "echo 'host replication all all md5' >> $PGDATA/pg_hba.conf"
 
-          # user 'npgsql_tests_scram' must be created with password encrypted as scram-sha-256 (which only applies after restart)
-          sudo -u postgres psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'"
+            brew services restart $postgreService
+            echo "Check PostgreSQL service is running"
+            i=5
+            COMMAND='pg_isready'
+            while [ $i -gt 0 ]; do
+                echo "Check PostgreSQL service status"
+                eval $COMMAND && break
+                ((i--))
+                if [ $i == 0 ]; then
+                    echo "PostgreSQL service not ready, all attempts exhausted"
+                    exit 1
+                fi
+                echo "PostgreSQL service not ready, wait 5 more sec, attempts left: $i"
+                sleep 5
+            done
+            psql -c "CREATE USER npgsql_tests_scram SUPERUSER PASSWORD 'npgsql_tests_scram'" postgres
 
       # TODO: Once test/Npgsql.Specification.Tests work, switch to just testing on the solution
       - name: Test
